In [1]:
import numpy as np

In [2]:
from numpy import argmax

In [3]:
from sklearn.datasets import load_iris

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential

In [6]:
iris_data=load_iris()

In [7]:
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
x=iris_data.data[:,:].astype('float32')

In [9]:
y=iris_data.target

In [10]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.10)

In [13]:
N_features=x_train.shape[1]

In [14]:
N_features

4

In [15]:
model=Sequential()

In [16]:
model.add(Dense(10,activation='relu',kernel_initializer='he_normal',input_shape=(N_features,)))
model.add(Dense(8,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(3,activation='softmax'))


In [17]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [18]:
model.fit(x_train,y_train,epochs=100,batch_size=30)

Epoch 1/100
5/5 [==============================] - 1s 5ms/step - loss: 1.3324 - accuracy: 0.2963
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2642 - accuracy: 0.2963
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2147 - accuracy: 0.2963
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1637 - accuracy: 0.2667
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1246 - accuracy: 0.2741
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1069 - accuracy: 0.2667
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0974 - accuracy: 0.2815
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0879 - accuracy: 0.3259
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0795 - accuracy: 0.3926
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0736 - accuracy: 0.4296
Epoch 11/100
5/5 [===========

In [19]:
new_data=[1.5,2.2,0.4,0.5]

In [20]:
y_pred=model.predict([new_data])

1/1 [==============================] - 0s 197ms/step


In [21]:
y_pred

array([[0.42132637, 0.37917966, 0.19949393]], dtype=float32)

In [22]:
Acc_score=model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 178ms/step - loss: 0.5217 - accuracy: 0.8667


In [23]:
Acc_score

[0.5216680765151978, 0.8666666746139526]